### PR TITLE
Limit time or mip gap

### PR DESCRIPTION
**Pull request by Wikunia**

### CODE REVIEW

**Comment by ccoffrin** [comment]
Two other useful limits are,
- stop after x feasible solutions are found 
- stop after a solution of quality x is found

**Comment by Wikunia** [comment]
@ccoffrin can you specify what you mean by quality x? Like specifying the value directly i.e feasible solution <= 10` ?

**Comment by ccoffrin** [comment]
By the quality of `x` I mean.  If you are minimizing the incumbent objective value is `<= x`.  If you are maximizing the incumbent, the objective value is ` >= x`.

**Comment by Wikunia** [comment]
@ccoffrin at the moment `best_obj_stop` returns `:UserLimit` if a better solution is found.
Don't know what the expected behavior is, if the best solution possible is actually worse than `best_obj_stop` should there be a notice or just run normally and `return :Optimal`?

**Comment by ccoffrin** [comment]
That’s a good question, it’s worth checking what gurobi does in that case.

My gut feeling that it should return the optimal solution and throw a
warning that it was not able to satisfy the desired the target objective
value.

**Comment by Wikunia** [comment]
@ccoffrin gurobi doesn't have that gut feeling :D They just ignore the stop value if they get the optimal value before. I think throwing a warning is reasonable anyway :)

**Comment by ccoffrin** [comment]
sounds good!

**Pull request merged**
